# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simG <- function(dnetwork, N, M) {
    .Call(`_CDatanet_simG`, dnetwork, N, M)
}

simGnorm <- function(dnetwork, N, M) {
    .Call(`_CDatanet_simGnorm`, dnetwork, N, M)
}

fGnormalise <- function(u, M) {
    .Call(`_CDatanet_fGnormalise`, u, M)
}

rem_non_fin <- function(net) {
    .Call(`_CDatanet_rem_non_fin`, net)
}

frVtoM <- function(u, N, M) {
    .Call(`_CDatanet_frVtoM`, u, N, M)
}

frVtoMnorm <- function(u, N, M) {
    .Call(`_CDatanet_frVtoMnorm`, u, N, M)
}

frMtoV <- function(u, N, M) {
    .Call(`_CDatanet_frMtoV`, u, N, M)
}

frMceiltoV <- function(u, N, M) {
    .Call(`_CDatanet_frMceiltoV`, u, N, M)
}

fcdlambdat <- function(lambda, nCa, a, b) {
    .Call(`_CDatanet_fcdlambdat`, lambda, nCa, a, b)
}

fcddlambdat <- function(lambda, nCa, a, b) {
    .Call(`_CDatanet_fcddlambdat`, lambda, nCa, a, b)
}

fcdlambda <- function(lambdat, nCa, a, b) {
    .Call(`_CDatanet_fcdlambda`, lambdat, nCa, a, b)
}

fcddlambda <- function(lambda, nCa, a, b) {
    .Call(`_CDatanet_fcddlambda`, lambda, nCa, a, b)
}

fL <- function(ZtLambda, lCa, nCa, delta, idelta, Rbar, R, n, sumn) {
    .Call(`_CDatanet_fL`, ZtLambda, lCa, nCa, delta, idelta, Rbar, R, n, sumn)
}

fLncond <- function(ZtLambda, lCa, nCa, delta, idelta, Rbar, R, n, sumn, nsimu) {
    .Call(`_CDatanet_fLncond`, ZtLambda, lCa, nCa, delta, idelta, Rbar, R, n, sumn, nsimu)
}

fye <- function(ye, Gye, G, lCa, nCa, igroup, ngroup, psi, lambda, delta, idelta, n, sumn, Rbar, R, tol, maxit) {
    .Call(`_CDatanet_fye`, ye, Gye, G, lCa, nCa, igroup, ngroup, psi, lambda, delta, idelta, n, sumn, Rbar, R, tol, maxit)
}

fyencond <- function(ye, Gye, G, lCa, nCa, igroup, ngroup, psi, lambda, delta, idelta, n, sumn, nsimu, Rbar, R, tol, maxit) {
    .Call(`_CDatanet_fyencond`, ye, Gye, G, lCa, nCa, igroup, ngroup, psi, lambda, delta, idelta, n, sumn, nsimu, Rbar, R, tol, maxit)
}

fy <- function(yst, maxyst, lCa, nCa, delta, idelta, n, sumn, Rbar, R) {
    .Call(`_CDatanet_fy`, yst, maxyst, lCa, nCa, delta, idelta, n, sumn, Rbar, R)
}

fmeffects <- function(ZtLambda, lambda, Gamma2, lCa, nCa, delta, idelta, sumn, Rbar, R) {
    .Call(`_CDatanet_fmeffects`, ZtLambda, lambda, Gamma2, lCa, nCa, delta, idelta, sumn, Rbar, R)
}

fdelta <- function(deltat, lambda, idelta, ndelta, nCa) {
    .Call(`_CDatanet_fdelta`, deltat, lambda, idelta, ndelta, nCa)
}

foptimREM <- function(ye, Gye, theta, lb_sl, ub_sl, X, G, lCa, nCa, igroup, ngroup, K, n, sumn, Rbar, R, idelta, ndelta, y, maxy, tol = 1e-13, maxit = 1e3L) {
    .Call(`_CDatanet_foptimREM`, ye, Gye, theta, lb_sl, ub_sl, X, G, lCa, nCa, igroup, ngroup, K, n, sumn, Rbar, R, idelta, ndelta, y, maxy, tol, maxit)
}

foptimREM_NPL <- function(Gye, theta, lb_sl, ub_sl, X, lCa, nCa, K, n, sumn, idelta, ndelta, Rbar, R, y, maxy, print = FALSE) {
    .Call(`_CDatanet_foptimREM_NPL`, Gye, theta, lb_sl, ub_sl, X, lCa, nCa, K, n, sumn, idelta, ndelta, Rbar, R, y, maxy, print)
}

fL_NPL <- function(ye, Gye, theta, X, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R) {
    invisible(.Call(`_CDatanet_fL_NPL`, ye, Gye, theta, X, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R))
}

fnewye <- function(ye, Gye, theta, X, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R, tol, maxit) {
    invisible(.Call(`_CDatanet_fnewye`, ye, Gye, theta, X, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R, tol, maxit))
}

cdnetLBFGS <- function(par, lb_sl, ub_sl, Gye, X, lCa, nCa, n, sumn, idelta, ndelta, Rbar, R, maxy, K, y, maxit = 300L, eps_f = 1e-13, eps_g = 1e-13, print = FALSE) {
    .Call(`_CDatanet_cdnetLBFGS`, par, lb_sl, ub_sl, Gye, X, lCa, nCa, n, sumn, idelta, ndelta, Rbar, R, maxy, K, y, maxit, eps_f, eps_g, print)
}

flogintphi <- function(Mean, lCa, nCa, a, b, sumn, S, simu) {
    .Call(`_CDatanet_flogintphi`, Mean, lCa, nCa, a, b, sumn, S, simu)
}

fcovCDI <- function(theta, Gamma2, Gye, X, ixWi, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R, S, ccov) {
    .Call(`_CDatanet_fcovCDI`, theta, Gamma2, Gye, X, ixWi, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R, S, ccov)
}

fcddEy <- function(theta, Gye, X, psi, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R, S) {
    .Call(`_CDatanet_fcddEy`, theta, Gye, X, psi, G, lCa, nCa, igroup, ngroup, K, n, sumn, idelta, ndelta, Rbar, R, S)
}

fdummies <- function(out, limit, M, n) {
    invisible(.Call(`_CDatanet_fdummies`, out, limit, M, n))
}

fdatar <- function(X, ftovar, nvar, K) {
    .Call(`_CDatanet_fdatar`, X, ftovar, nvar, K)
}

frMtoVbyCOL <- function(u, N, M) {
    .Call(`_CDatanet_frMtoVbyCOL`, u, N, M)
}

frMtoVbyCOLsym <- function(u, N, M) {
    .Call(`_CDatanet_frMtoVbyCOLsym`, u, N, M)
}

fmusum <- function(mu, nu, index, indexgr, M, N) {
    .Call(`_CDatanet_fmusum`, mu, nu, index, indexgr, M, N)
}

fmusumsym <- function(mu, index, indexgr, M, N) {
    .Call(`_CDatanet_fmusumsym`, mu, index, indexgr, M, N)
}

bayesmunu <- function(a, dx, invdxdx, beta0, mu0, nu0, smu20, snu20, rho0, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration, Print) {
    .Call(`_CDatanet_bayesmunu`, a, dx, invdxdx, beta0, mu0, nu0, smu20, snu20, rho0, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration, Print)
}

bayesmu <- function(a, dx, invdxdx, beta0, mu0, smu20, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration, sym, Print) {
    .Call(`_CDatanet_bayesmu`, a, dx, invdxdx, beta0, mu0, smu20, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration, sym, Print)
}

fhomobeta2f <- function(theta, a, dx, nvec, index, indexgr, M, maxit = 300L, eps_f = 1e-6, eps_g = 1e-5, hasX = TRUE, Print = TRUE) {
    .Call(`_CDatanet_fhomobeta2f`, theta, a, dx, nvec, index, indexgr, M, maxit, eps_f, eps_g, hasX, Print)
}

fhomobeta1f <- function(theta, a, dx, nvec, index, indexgr, M, maxit = 300L, eps_f = 1e-6, eps_g = 1e-5, hasX = TRUE, Print = TRUE) {
    .Call(`_CDatanet_fhomobeta1f`, theta, a, dx, nvec, index, indexgr, M, maxit, eps_f, eps_g, hasX, Print)
}

fhomobetasym <- function(theta, a, dx, nvec, index, indexgr, M, maxit = 300L, eps_f = 1e-6, eps_g = 1e-5, hasX = TRUE, Print = TRUE) {
    .Call(`_CDatanet_fhomobetasym`, theta, a, dx, nvec, index, indexgr, M, maxit, eps_f, eps_g, hasX, Print)
}

hdataF2L <- function(data, nvec, index, M) {
    .Call(`_CDatanet_hdataF2L`, data, nvec, index, M)
}

hdataF2U <- function(data, nvec, index, indexgr, M) {
    .Call(`_CDatanet_hdataF2U`, data, nvec, index, indexgr, M)
}

hdata2S <- function(data, nvec, index, indexgr, M) {
    .Call(`_CDatanet_hdata2S`, data, nvec, index, indexgr, M)
}

fySar <- function(y, Gy, G, eps, igroup, ngroup, psi, lambda) {
    invisible(.Call(`_CDatanet_fySar`, y, Gy, G, eps, igroup, ngroup, psi, lambda))
}

fySarRE <- function(y, Gye, ye, G, eps, igroup, ngroup, psi, lambda) {
    invisible(.Call(`_CDatanet_fySarRE`, y, Gye, ye, G, eps, igroup, ngroup, psi, lambda))
}

foptimSAR <- function(alphatilde, X, invXX, G, I, n, y, Gy, ngroup, FE, print) {
    .Call(`_CDatanet_foptimSAR`, alphatilde, X, invXX, G, I, n, y, Gy, ngroup, FE, print)
}

fSARjac <- function(lambda, s2, X, XX, Xbeta, G, I, igroup, ngroup, n, K, FE) {
    .Call(`_CDatanet_fSARjac`, lambda, s2, X, XX, Xbeta, G, I, igroup, ngroup, n, K, FE)
}

fybsar <- function(yb, Gyb, G, igroup, ngroup, psi, lambda) {
    invisible(.Call(`_CDatanet_fybsar`, yb, Gyb, G, igroup, ngroup, psi, lambda))
}

foptimSAR_RE <- function(alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K) {
    .Call(`_CDatanet_foptimSAR_RE`, alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K)
}

foptimSAR0_RE <- function(alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K) {
    .Call(`_CDatanet_foptimSAR0_RE`, alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K)
}

fyTobit <- function(yst, y, Gy, Ztlamda, G, eps, igroup, ngroup, psi, n, lambda, tol, maxit) {
    .Call(`_CDatanet_fyTobit`, yst, y, Gy, Ztlamda, G, eps, igroup, ngroup, psi, n, lambda, tol, maxit)
}

foptimTobit <- function(theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, npos, ngroup, I, W, n, igroup, print = FALSE) {
    .Call(`_CDatanet_foptimTobit`, theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, npos, ngroup, I, W, n, igroup, print)
}

fgradvecTobit <- function(theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, ngroup, I, W, n, indzero, indpos, igroup) {
    .Call(`_CDatanet_fgradvecTobit`, theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, ngroup, I, W, n, indzero, indpos, igroup)
}

fcovSTC <- function(theta, X, G2, I, W, K, n, y, Gy, indzero, indpos, igroup, ngroup, ccov) {
    .Call(`_CDatanet_fcovSTC`, theta, X, G2, I, W, K, n, y, Gy, indzero, indpos, igroup, ngroup, ccov)
}

fEytbit <- function(Ey, GEy, G, igroup, ngroup, psi, lambda, sigma, n, tol, maxit) {
    .Call(`_CDatanet_fEytbit`, Ey, GEy, G, igroup, ngroup, psi, lambda, sigma, n, tol, maxit)
}

foptimRE_TBT <- function(Ey, GEy, theta, yidpos, X, G, igroup, ngroup, npos, idpos, idzero, K, n, tol = 1e-13, maxit = 1e3L) {
    .Call(`_CDatanet_foptimRE_TBT`, Ey, GEy, theta, yidpos, X, G, igroup, ngroup, npos, idpos, idzero, K, n, tol, maxit)
}

foptimTBT_NPL <- function(yidpos, GEy, X, theta, npos, idpos, idzero, K, print = FALSE) {
    .Call(`_CDatanet_foptimTBT_NPL`, yidpos, GEy, X, theta, npos, idpos, idzero, K, print)
}

fLTBT_NPL <- function(Ey, GEy, G, X, theta, igroup, ngroup, n, K) {
    invisible(.Call(`_CDatanet_fLTBT_NPL`, Ey, GEy, G, X, theta, igroup, ngroup, n, K))
}

sartLBFGS <- function(par, yidpos, GEy, X, npos, idpos, idzero, K, maxit = 300L, eps_f = 1e-6, eps_g = 1e-5, print = FALSE) {
    .Call(`_CDatanet_sartLBFGS`, par, yidpos, GEy, X, npos, idpos, idzero, K, maxit, eps_f, eps_g, print)
}

fnewEyTBT <- function(Ey, GEy, G, igroup, ngroup, X, theta, K, n, tol, maxit) {
    invisible(.Call(`_CDatanet_fnewEyTBT`, Ey, GEy, G, igroup, ngroup, X, theta, K, n, tol, maxit))
}

fcovSTI <- function(n, GEy, theta, X, K, G, igroup, ngroup, ccov) {
    .Call(`_CDatanet_fcovSTI`, n, GEy, theta, X, K, G, igroup, ngroup, ccov)
}

