# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H <- function(G, igroup, ngroup, P, w, GPw, xb, A, alpha, sigma, N, R) {
    .Call('_CDatanet_H', PACKAGE = 'CDatanet', G, igroup, ngroup, P, w, GPw, xb, A, alpha, sigma, N, R)
}

updateP <- function(P, G, igroup, ngroup, w, GPw, xb, A, alpha, sigma, N, R, tol = 1e-13, maxit = 1e3L) {
    .Call('_CDatanet_updateP', PACKAGE = 'CDatanet', P, G, igroup, ngroup, w, GPw, xb, A, alpha, sigma, N, R, tol, maxit)
}

flogP <- function(P, w, GPw, xb, A, alpha, sigma, N, R) {
    .Call('_CDatanet_flogP', PACKAGE = 'CDatanet', P, w, GPw, xb, A, alpha, sigma, N, R)
}

floglih <- function(N, y, a, logP) {
    .Call('_CDatanet_floglih', PACKAGE = 'CDatanet', N, y, a, logP)
}

foptimREM <- function(P, theta, X, G, igroup, ngroup, w, a, A, K, N, R, y, tol = 1e-13, maxit = 1e3L) {
    .Call('_CDatanet_foptimREM', PACKAGE = 'CDatanet', P, theta, X, G, igroup, ngroup, w, a, A, K, N, R, y, tol, maxit)
}

#' foptimREMvec: vectorized form of foptimREM
#'               returns the likelihood for each
#'               individuals given the patameters
foptimREMvec <- function(P, theta, X, G, igroup, ngroup, w, a, A, K, N, R, y, tol = 1e-13, maxit = 1e3L) {
    .Call('_CDatanet_foptimREMvec', PACKAGE = 'CDatanet', P, theta, X, G, igroup, ngroup, w, a, A, K, N, R, y, tol, maxit)
}

#' foptimREM_nopeer: computes the likelihood with the constraint alpha = 0
#'                   theta does not contain alpha here: just the explanatory
#'                   variables and sigma.
foptimREM_nopeer <- function(theta, X, w, a, A, K, N, R, y) {
    .Call('_CDatanet_foptimREM_nopeer', PACKAGE = 'CDatanet', theta, X, w, a, A, K, N, R, y)
}

#' foptimREM_nopeervec: the vectorized form of foptimREM_nopeer
#'                      returns the likelihood for each individuals
#'                       given the patameters
foptimREM_nopeervec <- function(theta, X, w, a, A, K, N, R, y) {
    .Call('_CDatanet_foptimREM_nopeervec', PACKAGE = 'CDatanet', theta, X, w, a, A, K, N, R, y)
}

bREMCMC0 <- function(P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, nitcov, niteration, target, jumpmin, jumpmax, c, rtnormR) {
    .Call('_CDatanet_bREMCMC0', PACKAGE = 'CDatanet', P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, nitcov, niteration, target, jumpmin, jumpmax, c, rtnormR)
}

bREMCMC1 <- function(P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, nitcov, niteration, covmcmc, target, jumpmin, jumpmax, c, rtnormR) {
    .Call('_CDatanet_bREMCMC1', PACKAGE = 'CDatanet', P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, nitcov, niteration, covmcmc, target, jumpmin, jumpmax, c, rtnormR)
}

bREMCMC2 <- function(P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, niteration, covmcmc, target, jumpmin, jumpmax, c, rtnormR) {
    .Call('_CDatanet_bREMCMC2', PACKAGE = 'CDatanet', P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, niteration, covmcmc, target, jumpmin, jumpmax, c, rtnormR)
}

bREMCMC <- function(P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol = 1e-13, maxit = 1e3L, burnin = 5e2L, nitcov = 1e3L, niteration = 2e3L, covMCMC = NULL, target = 0.44, jumpmin = 1e-12, jumpmax = 1e2, c = 0.6, type = 0L) {
    .Call('_CDatanet_bREMCMC', PACKAGE = 'CDatanet', P0, theta0, X, G, igroup, w, a, A, K, N, R, y, mub, invVb, as, bs, tol, maxit, burnin, nitcov, niteration, covMCMC, target, jumpmin, jumpmax, c, type)
}

foptimTobit <- function(theta, X, G2, I2, K, y, Gy, idpos, idzero, Npos, ngroup) {
    .Call('_CDatanet_foptimTobit', PACKAGE = 'CDatanet', theta, X, G2, I2, K, y, Gy, idpos, idzero, Npos, ngroup)
}

fgradvecTobit <- function(theta, X, G2, I, W, K, N, y, Gy, indzero, indpos, igroup, ngroup) {
    .Call('_CDatanet_fgradvecTobit', PACKAGE = 'CDatanet', theta, X, G2, I, W, K, N, y, Gy, indzero, indpos, igroup, ngroup)
}

foptimSAR <- function(alphatilde, X, invXX, G, I, N, y, Gy, ngroup) {
    .Call('_CDatanet_foptimSAR', PACKAGE = 'CDatanet', alphatilde, X, invXX, G, I, N, y, Gy, ngroup)
}

