# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fL <- function(ZtLambda, delta, Rbar, n) {
    .Call(`_CDatanet_fL`, ZtLambda, delta, Rbar, n)
}

fLncond <- function(ZtLambda, delta, Rbar, n, nsimu) {
    .Call(`_CDatanet_fLncond`, ZtLambda, delta, Rbar, n, nsimu)
}

fyb <- function(yb, Gyb, G, igroup, ngroup, psi, lambda, delta, n, Rbar, tol, maxit) {
    .Call(`_CDatanet_fyb`, yb, Gyb, G, igroup, ngroup, psi, lambda, delta, n, Rbar, tol, maxit)
}

fybncond <- function(yb, Gyb, G, igroup, ngroup, psi, lambda, delta, n, nsimu, Rbar, tol, maxit) {
    .Call(`_CDatanet_fybncond`, yb, Gyb, G, igroup, ngroup, psi, lambda, delta, n, nsimu, Rbar, tol, maxit)
}

fy <- function(yst, maxyst, delta, n, Rbar) {
    .Call(`_CDatanet_fy`, yst, maxyst, delta, n, Rbar)
}

foptimREM <- function(yb, Gyb, theta, X, G, igroup, ngroup, K, n, Rbar, y, maxy, tol = 1e-13, maxit = 1e3L) {
    .Call(`_CDatanet_foptimREM`, yb, Gyb, theta, X, G, igroup, ngroup, K, n, Rbar, y, maxy, tol, maxit)
}

foptimREMncond1 <- function(yb, Gyb, theta, X, Simu1, nsimu, G, igroup, ngroup, K, n, Rbar, y, maxy, tol = 1e-13, maxit = 1e3L) {
    .Call(`_CDatanet_foptimREMncond1`, yb, Gyb, theta, X, Simu1, nsimu, G, igroup, ngroup, K, n, Rbar, y, maxy, tol, maxit)
}

foptimREM_NPL <- function(Gyb, theta, X, Rbar, maxy, K, n, y) {
    .Call(`_CDatanet_foptimREM_NPL`, Gyb, theta, X, Rbar, maxy, K, n, y)
}

fL_NPL <- function(yb, Gyb, G, igroup, ngroup, X, theta, Rbar, K, n) {
    invisible(.Call(`_CDatanet_fL_NPL`, yb, Gyb, G, igroup, ngroup, X, theta, Rbar, K, n))
}

fnewyb <- function(yb, Gyb, G, igroup, ngroup, X, theta, Rbar, K, n, tol, maxit) {
    invisible(.Call(`_CDatanet_fnewyb`, yb, Gyb, G, igroup, ngroup, X, theta, Rbar, K, n, tol, maxit))
}

foptimREM_NPLncond1 <- function(Gyb, theta, X, Simu1, nsimu, Rbar, maxy, K, n, y) {
    .Call(`_CDatanet_foptimREM_NPLncond1`, Gyb, theta, X, Simu1, nsimu, Rbar, maxy, K, n, y)
}

fL_NPLncond1 <- function(yb, Gyb, G, igroup, ngroup, X, theta, Simu1, nsimu, Rbar, K, n) {
    invisible(.Call(`_CDatanet_fL_NPLncond1`, yb, Gyb, G, igroup, ngroup, X, theta, Simu1, nsimu, Rbar, K, n))
}

foptimREM_NPLncond2 <- function(Gyb, theta, X, Simu1, Simu2, nsimu, Rbar, maxy, K, n, y) {
    .Call(`_CDatanet_foptimREM_NPLncond2`, Gyb, theta, X, Simu1, Simu2, nsimu, Rbar, maxy, K, n, y)
}

fL_NPLncond2 <- function(yb, Gyb, G, igroup, ngroup, X, theta, Simu1, Simu2, nsimu, Rbar, K, n) {
    invisible(.Call(`_CDatanet_fL_NPLncond2`, yb, Gyb, G, igroup, ngroup, X, theta, Simu1, Simu2, nsimu, Rbar, K, n))
}

flogintphi <- function(n, S, a, b, Mean, simu, igroup, ngroup) {
    .Call(`_CDatanet_flogintphi`, n, S, a, b, Mean, simu, igroup, ngroup)
}

fcovCDI <- function(n, Gyb, theta, X, Rbar, K, S, G, igroup, ngroup, ccov) {
    .Call(`_CDatanet_fcovCDI`, n, Gyb, theta, X, Rbar, K, S, G, igroup, ngroup, ccov)
}

fdummies <- function(out, limit, M, n) {
    invisible(.Call(`_CDatanet_fdummies`, out, limit, M, n))
}

fmusum <- function(mu, nu, index, indexgr, M, N) {
    .Call(`_CDatanet_fmusum`, mu, nu, index, indexgr, M, N)
}

updategparms1 <- function(a, dx, invdxdx, beta0, mu0, nu0, smu20, snu20, rho0, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration) {
    .Call(`_CDatanet_updategparms1`, a, dx, invdxdx, beta0, mu0, nu0, smu20, snu20, rho0, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration)
}

updategparms2 <- function(a, dx, invdxdx, beta0, mu0, nu0, smu20, snu20, rho0, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration) {
    .Call(`_CDatanet_updategparms2`, a, dx, invdxdx, beta0, mu0, nu0, smu20, snu20, rho0, index, indexgr, INDEXgr, nfix, N, M, K, Kx, nvec, n, iteration)
}

fySar <- function(y, Gy, G, eps, igroup, ngroup, psi, lambda) {
    invisible(.Call(`_CDatanet_fySar`, y, Gy, G, eps, igroup, ngroup, psi, lambda))
}

foptimSAR <- function(alphatilde, X, invXX, G, I, n, y, Gy, ngroup) {
    .Call(`_CDatanet_foptimSAR`, alphatilde, X, invXX, G, I, n, y, Gy, ngroup)
}

foptimSAR0 <- function(alphatilde, X, invXX, G, I, n, y, Gy, ngroup) {
    .Call(`_CDatanet_foptimSAR0`, alphatilde, X, invXX, G, I, n, y, Gy, ngroup)
}

fSARjac <- function(lambda, s2, X, XX, Xbeta, G, I, igroup, ngroup, n, K) {
    .Call(`_CDatanet_fSARjac`, lambda, s2, X, XX, Xbeta, G, I, igroup, ngroup, n, K)
}

fybsar <- function(yb, Gyb, G, igroup, ngroup, psi, lambda) {
    invisible(.Call(`_CDatanet_fybsar`, yb, Gyb, G, igroup, ngroup, psi, lambda))
}

foptimSAR_RE <- function(alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K) {
    .Call(`_CDatanet_foptimSAR_RE`, alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K)
}

foptimSAR0_RE <- function(alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K) {
    .Call(`_CDatanet_foptimSAR0_RE`, alphatilde, X, G, I, y, Gy, igroup, ngroup, n, K)
}

fyTobit <- function(yst, y, Gy, Ztlamda, G, eps, igroup, ngroup, psi, n, lambda, tol, maxit) {
    .Call(`_CDatanet_fyTobit`, yst, y, Gy, Ztlamda, G, eps, igroup, ngroup, psi, n, lambda, tol, maxit)
}

foptimTobit <- function(theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, npos, ngroup, I, W, n, igroup) {
    .Call(`_CDatanet_foptimTobit`, theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, npos, ngroup, I, W, n, igroup)
}

foptimTobit0 <- function(theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, npos, ngroup, I, W, n, igroup) {
    .Call(`_CDatanet_foptimTobit0`, theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, npos, ngroup, I, W, n, igroup)
}

fgradvecTobit <- function(theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, ngroup, I, W, n, indzero, indpos, igroup) {
    .Call(`_CDatanet_fgradvecTobit`, theta, X, logdetA2, alphatilde, G2, I2, K, y, Gy, idpos, idzero, ngroup, I, W, n, indzero, indpos, igroup)
}

fcovSTC <- function(theta, X, G2, I, W, K, n, y, Gy, indzero, indpos, igroup, ngroup, ccov) {
    .Call(`_CDatanet_fcovSTC`, theta, X, G2, I, W, K, n, y, Gy, indzero, indpos, igroup, ngroup, ccov)
}

fybtbit <- function(yb, Gyb, G, igroup, ngroup, psi, lambda, sigma, n, tol, maxit) {
    .Call(`_CDatanet_fybtbit`, yb, Gyb, G, igroup, ngroup, psi, lambda, sigma, n, tol, maxit)
}

foptimRE_TBT <- function(yb, Gyb, theta, yidpos, X, G, igroup, ngroup, npos, idpos, idzero, K, n, tol = 1e-13, maxit = 1e3L) {
    .Call(`_CDatanet_foptimRE_TBT`, yb, Gyb, theta, yidpos, X, G, igroup, ngroup, npos, idpos, idzero, K, n, tol, maxit)
}

foptimTBT_NPL <- function(yidpos, Gyb, X, theta, npos, idpos, idzero, K) {
    .Call(`_CDatanet_foptimTBT_NPL`, yidpos, Gyb, X, theta, npos, idpos, idzero, K)
}

fLTBT_NPL <- function(yb, Gyb, G, X, theta, igroup, ngroup, n, K) {
    invisible(.Call(`_CDatanet_fLTBT_NPL`, yb, Gyb, G, X, theta, igroup, ngroup, n, K))
}

fnewybTBT <- function(yb, Gyb, G, igroup, ngroup, X, theta, K, n, tol, maxit) {
    invisible(.Call(`_CDatanet_fnewybTBT`, yb, Gyb, G, igroup, ngroup, X, theta, K, n, tol, maxit))
}

fcovSTI <- function(n, Gyb, theta, X, K, G, igroup, ngroup, ccov) {
    .Call(`_CDatanet_fcovSTI`, n, Gyb, theta, X, K, G, igroup, ngroup, ccov)
}

